[package]
name = "vehicle-pathfinding"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
notan = "0.12.0"
pathfinding = "4.9.1"
splines = { version = "4.3.1", features = ["glam"] }
geo = "0.28.0"
mimalloc = "0.1.42"
typed-arena = "2.0.2"
binary-heap-plus = "0.5.0"
